name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "tools/**"
      - "wrangler.toml"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # OPTIONAL: build users.json from your spreadsheet if it's present
      - name: Build users.json from spreadsheet (optional)
        if: ${{ hashFiles('data/Replit Users Committee Members.xlsx') != '' }}
        run: |
          npm i xlsx@0.18.5
          node tools/xlsx-to-users-json.mjs "data/Replit Users Committee Members.xlsx" > api/users.json

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Publish Worker
        run: wrangler deploy --config wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
